### ISSUE TITLE
bug: build is silently wonky when metadata not present

### ISSUE THREAD

**Issue by pmengelbert** [Azure/dalec#69]
The following spec builds without issue with the command `docker build -f spec.yaml --output=type=local,dest=/tmp/out .` (default target=mariner2/container):
```yaml
# syntax=local/dalec:latest
name: dalec-test-fixutre-local-context
description: A test fixture for checking local context sources
website: https://www.github.com/Azure/dalec
version: 0.0.1
revision: 1
vendor: Microsoft

packager: Microsoft <support@microsoft.com>
license: Apache 2.0
sources:
  src:
    context:
      path: test/fixtures

build:
  env:
    HELLO: "world"
  steps:
    - command: |
        echo "yes" > src/goodbye
        chmod +x src/goodbye

artifacts:
  binaries:
    src/goodbye:

tests:
  - name: Check bin
    files:
      /usr/bin/goodbye:
        permissions: 0755
```
But remove the `name: <...>` line and the test fails:
"
ERROR: failed to solve: FAILED: mariner2/Check bin: stat failed: /usr/bin/goodbye: lstat /var/lib/docker/tmp/buildkit-mount2993361398/usr/bin/goodbye: no such file or directory
"

When `name` is missing, the error is the most confusing because it silently **does not run** the build steps. Nor does it take any action based on the contents of `artifacts`.

Other failures occur when any of description, website, version, vendor, packager, or license is not provided. They are different failures and I'm guessing it fails because the template is filled out wrong when the strings are empty. the failure looks like this:
```
 => ERROR sh -c trap '/tmp/chroot-cleanup.sh > /dev/null' EXIT; ma  6.1s
------
 > sh -c trap '/tmp/chroot-cleanup.sh > /dev/null' EXIT; make -j8 build-packages || (set -x; ls -lh /root/.cache/mariner2-toolkit-rpm-cache/cache; cat /build/build/logs/pkggen/rpmbuilding/*; ls -lh ${CACHED_RPMS_DIR}/cache; exit 1):
0.273 DEBU[0000][srpmpacker] Begin recording timestamp for srpmpacker    
0.274 DEBU[0000][specreader] Begin recording timestamp for specreader    
0.274 DEBU[0000][specreader] Select chroot -> /tmp/chroot/dalec2         
0.274 DEBU[0000][specreader] cleanup Chroot -> /tmp/chroot/dalec2        
0.274 DEBU[0000][specreader] Using (/usr/bin/gzip) to extract tar        
0.274 DEBU[0000][specreader] Executing: [tar -I /usr/bin/gzip -xf /build/build/worker/worker_chroot.tar.gz -C /tmp/chroot/dalec2]
0.296 DEBU[0000][srpmpacker] chroot /tmp/chroot/dalec2 currently used    
0.296 DEBU[0000][srpmpacker] Select chroot -> /tmp/chroot/dalec0         
0.296 DEBU[0000][srpmpacker] cleanup Chroot -> /tmp/chroot/dalec0        
0.297 DEBU[0000][srpmpacker] Using (/usr/bin/gzip) to extract tar        
0.297 DEBU[0000][srpmpacker] Executing: [tar -I /usr/bin/gzip -xf /build/build/worker/worker_chroot.tar.gz -C /tmp/chroot/dalec0]
5.410 DEBU[0005][specreader] Executing: [cp -r -a /build/SPECS/dalec-test-fixutre-local-context /tmp/chroot/dalec2/build/SPECS/dalec-test-fixutre-local-context]
5.412 DEBU[0005][specreader] Executing: [cp -a /build/build/INTERMEDIATE_SRPMS/pack_list.txt /tmp/chroot/dalec2/build/build/INTERMEDIATE_SRPMS/pack_list.txt]
5.415 INFO[0005][specreader] Parsing SPECs inside a chroot environment   
5.415 DEBU[0005][specreader] Entering Chroot: '/tmp/chroot/dalec2'       
5.415 DEBU[0005][specreader] Executing: [rpmspec --srpm -q --target x86_64 --qf %{NAME}-%{VERSION}-%{RELEASE}.src.rpm -D with_check 0 -D dist .cm2 -D _sourcedir /build/SPECS/dalec-test-fixutre-local-context /build/SPECS/dalec-test-fixutre-local-context/dalec-test-fixutre-local-context.spec]
5.419 WARN[0005][specreader] error: line 7: Empty tag: License:
5.419 error: query of specfile /build/SPECS/dalec-test-fixutre-local-context/dalec-test-fixutre-local-context.spec failed, can't parse
5.419 DEBU[0005][specreader] Waiting for outstanding workers to finish   
5.419 DEBU[0005][specreader] Exiting Chroot: '/tmp/chroot/dalec2'        
5.419 DEBU[0005][specreader] Release chroot -> /tmp/chroot/dalec2/chroot-used
5.419 PANI[0005][specreader] failed to parse native specs (exit status 1)
5.447 DEBU[0005][specreader] Completed recording timestamp, results written to /build/build/timestamp/specreader.jsonl
5.449 panic: (*logrus.Entry) 0xc0001c2380
5.449
5.449 goroutine 1 [running]:
5.449 github.com/sirupsen/logrus.(*Entry).log(0xc0001c2000, 0x0, {0xc0001aa660, 0x2c})
5.449   /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x4d6
5.449 github.com/sirupsen/logrus.(*Entry).Log(0xc0001c2000, 0x0, {0xc00031fd18?, 0x534c2b?, 0xc00037a0c0?})
5.449   /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x4f
5.449 github.com/sirupsen/logrus.(*Entry).Logln(0xc0001c2000, 0x0, {0xc00031fdb0?, 0x1f?, 0x7ffd0efc8c6c?})
5.449   /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:394 +0x85
5.449 github.com/sirupsen/logrus.(*Logger).Logln(0xc00037a080, 0x0, {0xc00031fdb0, 0x1, 0x1})
5.449   /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:298 +0x65
5.449 github.com/sirupsen/logrus.(*Logger).Panicln(...)
5.449   /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:339
5.449 github.com/microsoft/CBL-Mariner/toolkit/tools/internal/logger.PanicOnError({0x8688a0, 0xc0001a8100}, {0x0?, 0x4?, 0x7ffd0efc8e05?})
5.449   /build/toolkit/tools/internal/logger/log.go:129 +0xc9
5.449 main.main()
5.449   /build/toolkit/tools/specreader/specreader.go:121 +0x5c5
5.449 DEBU[0005][srpmpacker] Executing: [cp -r -a /build/SPECS/dalec-test-fixutre-local-context /tmp/chroot/dalec0/specs/dalec-test-fixutre-local-context]
5.449 make: *** [/build/toolkit/scripts/pkggen.mk:94: /build/build/pkg_artifacts/specs.json] Error 2
5.449 make: *** Waiting for unfinished jobs....
5.451 DEBU[0005][srpmpacker] Executing: [cp -a /build/build/INTERMEDIATE_SRPMS/pack_list.txt /tmp/chroot/dalec0/output/pack_list.txt]
5.451 DEBU[0005][srpmpacker] Copying '/etc/resolv.conf' to worker '/tmp/chroot/dalec0/etc/resolv.conf'
5.451 DEBU[0005][srpmpacker] Copying (/etc/resolv.conf) -> (/tmp/chroot/dalec0/etc/resolv.conf)
5.451 DEBU[0005][srpmpacker] Executing: [cp --preserve=mode /etc/resolv.conf /tmp/chroot/dalec0/etc/resolv.conf]
5.452 INFO[0005][srpmpacker] Packing SRPMs inside a chroot environment   
5.452 DEBU[0005][srpmpacker] Entering Chroot: '/tmp/chroot/dalec0'       
5.452 INFO[0005][srpmpacker] Finding all SPEC files                      
5.452 INFO[0005][srpmpacker] Calculating SPECs to repack                 
5.452 DEBU[0005][srpmpacker] Executing: [rpmspec --srpm -q --target x86_64 --qf %{NAME}-%{VERSION}-%{RELEASE}.src.rpm -D with_check 0 -D dist .cm2 -D _sourcedir /specs/dalec-test-fixutre-local-context /specs/dalec-test-fixutre-local-context/dalec-test-fixutre-local-context.spec]
5.457 WARN[0005][srpmpacker] error: line 7: Empty tag: License:
5.457 error: query of specfile /specs/dalec-test-fixutre-local-context/dalec-test-fixutre-local-context.spec failed, can't parse
5.458 ERRO[0005][srpmpacker] Failed to check (/specs/dalec-test-fixutre-local-context/dalec-test-fixutre-local-context.spec). Error: exit status 1
5.458 DEBU[0005][srpmpacker] Waiting for outstanding workers to finish   
5.458 DEBU[0005][srpmpacker] Exiting Chroot: '/tmp/chroot/dalec0'        
5.458 DEBU[0005][srpmpacker] Release chroot -> /tmp/chroot/dalec0/chroot-used
5.458 PANI[0005][srpmpacker] exit status 1                               
5.459 DEBU[0005][srpmpacker] Completed recording timestamp, results written to /build/build/timestamp/srpm_packer.jsonl
5.461 panic: (*logrus.Entry) 0xc0001dc4d0
5.461
5.461 goroutine 1 [running]:
5.461 github.com/sirupsen/logrus.(*Entry).log(0xc0001dc000, 0x0, {0xc0002ce480, 0xd})
5.461   /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x4d6
5.461 github.com/sirupsen/logrus.(*Entry).Log(0xc0001dc000, 0x0, {0xc000055bb0?, 0x65c14b?, 0xc0000b81c0?})
5.461   /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x4f
5.461 github.com/sirupsen/logrus.(*Entry).Logln(0xc0001dc000, 0x0, {0xc000055c48?, 0xa?, 0x0?})
5.461   /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:394 +0x85
5.461 github.com/sirupsen/logrus.(*Logger).Logln(0xc0000b8180, 0x0, {0xc000055c48, 0x1, 0x1})
5.461   /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:298 +0x65
5.461 github.com/sirupsen/logrus.(*Logger).Panicln(...)
5.461   /root/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/logger.go:339
5.461 github.com/microsoft/CBL-Mariner/toolkit/tools/internal/logger.PanicOnError({0x7ff360, 0xc0001ec0c0}, {0x0?, 0x0?, 0x0?})
5.461   /build/toolkit/tools/internal/logger/log.go:129 +0xc9
5.461 main.main()
5.461   /build/toolkit/tools/srpmpacker/srpmpacker.go:194 +0x975
5.463 make: *** [/build/toolkit/scripts/srpm_pack.mk:88: /build/build/make_status/build_srpms.flag] Error 2
5.463 + ls -lh /root/.cache/mariner2-toolkit-rpm-cache/cache
5.464 total 0
5.464 + cat '/build/build/logs/pkggen/rpmbuilding/*'
5.464 cat: '/build/build/logs/pkggen/rpmbuilding/*': No such file or directory
5.465 + ls -lh /root/.cache/mariner2-toolkit-rpm-cache/cache
5.465 total 0
5.465 + exit 1
------
spec.yml:1
--------------------
   1 | >>> # syntax=local/dalec:latest
   2 |     name: dalec-test-fixutre-local-context
   3 |     description: A test fixture for checking local context sources
--------------------
ERROR: failed to solve: FAILED: mariner2/Check bin: process "sh -c trap '/tmp/chroot-cleanup.sh > /dev/null' EXIT; make -j8 build-packages || (set -x; ls -lh /root/.cache/mariner2-toolkit-rpm-cache/cache; cat /build/build/logs/pkggen/rpmbuilding/*; ls -lh ${CACHED_RPMS_DIR}/cache; exit 1)" did not complete successfully: exit code: 1

```

**Comment by cpuguy83** [comment]
Validation was added for this in #161
